# Generated by Django 5.2.17 on 2026-08-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('DTH', 'DTH Receiver'), ('TV', 'LED TV'), ('MIXER', 'Mixer Grinder'), ('FAN', 'Fan'), ('COOLER', 'Cooler'), ('INDUCTION', 'Induction Cooker'), ('ACCESSORY', 'Electronics Accessory'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('condition', models.CharField(choices=[('NEW', 'New Product'), ('REFURBISHED', 'Refurbished Product'), ('WHOLESALE', 'Wholesale Bulk Product')], default='NEW', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wholesale_min_qty', models.PositiveIntegerField(default=10)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, default='', help_text='External or placeholder image URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_wholesale', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Purchase Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
